"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import py2app
from setuptools import setup

APP = ['C:\\Users\\Ivan\\Desktop\\chat-avenue\\start.py']
DATA_FILES = [
    'C:\\Users\\Ivan\\Desktop\\chat-avenue\\src\\doing.py',
    'C:\\Users\\Ivan\\Desktop\\chat-avenue\\src\\emailverification.py',
    'C:\\Users\\Ivan\\Desktop\\chat-avenue\\src\\making.py',
    'C:\\Users\\Ivan\\Desktop\\chat-avenue\\src\\recaptcha_solver.py'
]
OPTIONS = {
    'packages': ['string', 'requests', 'selenium', 'os', 'sys', 'time', 'random', 'python_anticaptcha']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
